name: github actions 자동 배포

on:
  push:
    branches:
      - main

jobs:
  autodeploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: github repository 가져오기
        uses: actions/checkout@v4

      - name: jdk17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

